@startuml Nominal Generator State Machine
    title Nominal Generator State Machine
    [*] --> initial
    initial --> working
    working --> working :voltage_out:=voltage_out
   
    working --> failed : voltage_out:= voltage_out - decr
    failed --> failed : voltage_out:= voltage_out - decr
    initial:
    working:
    
@endstartuml