@startuml Battery State Machine
    title Battery Nominal State Machine
    [*] --> initial: voltage_out:=1.5
    initial --> charging
    charging --> charging: voltage_in>=1.1
    charging --> discharging: voltage_in<1.1
    discharging --> charging: voltage_in>=1.1
    discharging --> discharging: voltage_in<1.1
    
    charging --> failed
    discharging --> failed
    failed --> failed 
    state charging: voltage_out:=min(voltage_out + 0.1, 1.5)
    state discharging: voltage_out:=max(voltage_out - 0.1, 0)
    state initial 
    
@enduml