@startuml Nominal Sensor State Machine
    title Nominal Sensor State Machine 
    [*] --> initial: reading:=40.0
    initial --> working 
    working --> working : 30 <= reading & reading >=50
    working --> failed : wrong reading
    failed --> failed : wrong reading
    state initial: 
    state working: 30.0<=reading<=50.0
    state failed: reading <30.0 | \nreading > 50.0
    
@enduml